name: Java CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # macos-latest
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: windows-latest
            release_suffix: win

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: installDist

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release-${{ matrix.release_suffix }}.zip'
          path: './desktop/build/install/desktop'

      - uses: actions/upload-artifact@v2
        with:
          name: release-${{ matrix.os }}
          path: '*.zip'

  release:
    name: "Prelease"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2

      - name: Display fetched artifacts
        run: ls -R


      - name: Upload release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            release-windows-latest/*.zip
            release-ubuntu-latest/*.zip
          # release-macos-latest/*.zip